What is torch (PyTorch)?

The torch package in PyTorch is the core library used for deep learning.

It provides:

A data structure called tensors (multi-dimensional arrays)
Mathematical operations on tensors
Tools for GPU acceleration (CUDA)
Utilities for saving, loading, and managing models
Support for automatic differentiation (training neural networks)

#Tensors

In [1]:
import torch 
import numpy as np 

Initializing a Tensor
Tensors can be initialized in various ways. Take a look at the following examples:

Directly from data

Tensors can be created directly from data. The data type is automatically inferred.

In [ ]:
data = [[1,2],[3,4]] #list (we transforme the list to tensor )
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


From a NumPy array
    Check type: is_tensor()
    Create tensors: tensor(), zeros(), ones(), rand()
    Convert data: from_numpy(), as_tensor()

PyTorch offers many ways to create tensors:
    torch.zeros() → filled with 0
    torch.ones() → filled with 1
    torch.rand() → random values (0 to 1)
    torch.randn() → random normal distribution
    torch.arange() → sequence of numbers
    torch.eye() → identity matrix

In [ ]:
# we transfome the numpy to tensor 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


create new tensors based on an existing tensor (x_data) in PyTorch.
Creates a new tensor filled with 1s, but with the same shape and properties as x_data

“retains the properties of x_data” means:
same shape (size)
same device (CPU or GPU)
same layout

In [ ]:
x_data = [[2, 5],
          [7, 9]]
x_data = torch.tensor(x_data) # make x_data a tensor 
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



reates a new tensor with:

same shape as x_data
same  device as x_data 
same layout 

but filled with random numbers (0 to 1)

In [13]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"a random Tensor: \n {x_rand} \n")

a random Tensor: 
 tensor([[0.0233, 0.1107],
        [0.4795, 0.1921]]) 



shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.
x.shape => it's a attribute returne a tuple (1,2,...)

In [ ]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")   

Random Tensor: 
 tensor([[0.6852, 0.0564, 0.4972],
        [0.7692, 0.4424, 0.4188]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Attributes of a Tensor
    Tensor attributes describe their shape, datatype, and the device on which they are stored.
    shape it's describe the forme of the tensor 
    datatype it(s describe the type of the tensor int ,float .fp32,fl16 ,fp8)

In [5]:
tensor = torch.rand(3,4)
print(f"the shape of tensor is { tensor.shape} \n")
print(f"the datatype of tensor is {tensor.dtype} \n")
print(f"the device tensor is stored on {tensor.device} \n")

if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"the device tensor is stored on {tensor.device} \n")
    

the shape of tensor is torch.Size([3, 4]) 

the datatype of tensor is torch.float32 

the device tensor is stored on cpu 

the device tensor is stored on cuda:0 



Operations on Tensors
Over 1200 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here.

Each of these operations can be run on the CPU and Accelerator such as CUDA, MPS, MTIA, or XPU. If you’re using Colab, allocate an accelerator by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using .*to* method (after checking for accelerator availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!


Math operations:

3. addition, subtraction, multiplication, division
power, exponential, logarithm
trigonometric functions
Matrix operations:
matmul() → matrix multiplication
mm() → matrix multiply
dot() → dot product
Reductions:
sum() 
mean()
max()
min()


4. Indexing and Shape Operations

You can reshape and modify tensors:

reshape() → change shape
view() → reshape (memory shared)
transpose() → swap dimensions
squeeze() → remove empty dimensions
unsqueeze() → add dimension
cat() / stack() → combine tensors

6. 5. Random Sampling

PyTorch can generate random values:

rand() → uniform random [0,1)
randn() → normal distribution
randint() → random integers
manual_seed() → reproducible randomness

to see all the operation that torch give its https://docs.pytorch.org/docs/2.12/torch.html

In [6]:
#we move our tensor to the accelerator if available 
if torch.cuda.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    print(f"the device tensor is stored on {tensor.device} \n")

the device tensor is stored on cuda:0 



In [12]:
#sum, sub between tensors
tensor1 = torch.randn(3,4)
print(f"first tensor is \n {tensor1} \n")
tensor2 = torch.randn(3,4)
print(f"the second tensor is \n {tensor2 } \n")
tensor_sum = tensor1 + tensor2 
tensor_sub = tensor1 - tensor2
print(f"the sum of the two tensors is \n {tensor_sum} \n")
print(f"the difference of the two tensors is \n {tensor_sub} \n")  

first tensor is 
 tensor([[-0.8409, -0.3405, -0.4894,  0.7617],
        [ 1.0295,  0.2918, -2.0666, -1.4414],
        [-0.4596,  0.2742,  1.2104,  0.2097]]) 

the second tensor is 
 tensor([[ 1.0619,  0.7672,  0.9661,  1.5759],
        [ 0.3208,  0.1612, -2.0033,  0.3432],
        [-0.7488, -1.4398, -0.0801,  0.5528]]) 

the sum of the two tensors is 
 tensor([[ 0.2210,  0.4267,  0.4767,  2.3376],
        [ 1.3502,  0.4530, -4.0699, -1.0981],
        [-1.2084, -1.1656,  1.1303,  0.7625]]) 

the difference of the two tensors is 
 tensor([[-1.9029, -1.1078, -1.4555, -0.8142],
        [ 0.7087,  0.1306, -0.0634, -1.7846],
        [ 0.2892,  1.7140,  1.2904, -0.3431]]) 



In Python (and in PyTorch), API means:

Application Programming Interface

But more simply:

An API is the set of functions, classes, and tools you use to interact with a library like PyTorch.

Tensor creation API
    torch.tensor()
    torch.ones()
    torch.zeros()
    torch.rand()

Math API
    torch.add()
    torch.mul()
    torch.matmul()
    torch.sum()

GPU api 
    tensor.to("cuda")
    torch.cuda.is_available()


Standard Numpy-like indexing and slicing 

In [24]:
tensor = torch.ones(4,4)
print(f"the original tensor is \n {tensor} \n")
tensor[:,1] = 0
print(f"the modified tensor is \n {tensor} \n")
print(f"first row :{tensor[0]} \n")
print(f"first column : {tensor[:,0]} \n")
print(f"last column : {tensor[:,-1]} \n ")

the original tensor is 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

the modified tensor is 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

first row :tensor([1., 0., 1., 1.]) 

first column : tensor([1., 1., 1., 1.]) 

last column : tensor([1., 1., 1., 1.]) 
 


concating Tensor using `torhc.cat`

Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining operator that is subtly different from torch.cat.

In [16]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.7648, 0.9040, 0.8457, 0.8922, 0.7648, 0.9040, 0.8457, 0.8922, 0.7648,
         0.9040, 0.8457, 0.8922],
        [0.8522, 0.4985, 0.3396, 0.4085, 0.8522, 0.4985, 0.3396, 0.4085, 0.8522,
         0.4985, 0.3396, 0.4085],
        [0.9263, 0.8820, 0.8058, 0.0039, 0.9263, 0.8820, 0.8058, 0.0039, 0.9263,
         0.8820, 0.8058, 0.0039]], device='cuda:0')


Arithmetic operations

In [ ]:
# return the transpose of tensor 
#@ is the matrix multiplication operator
y1 = tensor @ tensor.T
print(f"the result of matrix multiplication is \n {y1} \n")
y2 = tensor.matmul(tensor.T)
print(f"the result of matrix multiplication is \n {y2} \n")

#Element-wise multiplication
y3 = torch.rand_like(tensor)
z1 = y3 * tensor
print(f"the result of elementwise multiplication is \n {z1} \n")
z2 = y3.mul(tensor)
print(f"the result of elementwise multiplication is \n {z2} \n")    


#Do NOT create a new tensor — store the result directly in z3”
z3 = torch.rand_like(tensor)
torch.mul(tensor, z3, out=z3)
print(f"the result of elementwise multiplication is \n {z3} \n")



the result of matrix multiplication is 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

the result of matrix multiplication is 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

the result of elementwise multiplication is 
 tensor([[0.7419, 0.0000, 0.6940, 0.0525],
        [0.3723, 0.0000, 0.4160, 0.7066],
        [0.6421, 0.0000, 0.0458, 0.1731],
        [0.3636, 0.0000, 0.5344, 0.3566]]) 

the result of elementwise multiplication is 
 tensor([[0.7419, 0.0000, 0.6940, 0.0525],
        [0.3723, 0.0000, 0.4160, 0.7066],
        [0.6421, 0.0000, 0.0458, 0.1731],
        [0.3636, 0.0000, 0.5344, 0.3566]]) 

the result of elementwise multiplication is 
 tensor([[0.6081, 0.0000, 0.7408, 0.9732],
        [0.3764, 0.0000, 0.9204, 0.0638],
        [0.6587, 0.0000, 0.8847, 0.2072],
        [0.3471, 0.0000, 0.4827, 0.4290]]) 



Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`:

In [17]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

8.123590469360352 <class 'float'>


In PyTorch, in-place operations ( _ ) are operations that modify a tensor directly in memory instead of creating a new one

They are identified by a _ (underscore) at the end of the function name.

exemple 
copy_()
    x.copy_(y)
    copies values of y into x
    overwrites x


t_( ) transpose in-place
    x.t_()
    👉 Transposes x directly
    👉 No new tensor created


✔ Advantages:
saves memory
faster execution
useful for large tensors (deep learning)
❌ Risks:
can break gradient tracking
can overwrite needed values
harder to debug

In [33]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Bridge with NumPy

Tensor to NumPy array

In [34]:
t = torch.ones(5)
print(f"{t} \n")
n = t.numpy()
print(f"{n} \n")

tensor([1., 1., 1., 1., 1.]) 

[1. 1. 1. 1. 1.] 



In [ ]:
t.add_(1) #change t in place
print(f"t: {t}")
print(f"n: {n}")

#A change in the tensor reflects in the NumPy array.

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor

In [68]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t} \n")
print(f"n: {n} \n")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 

n: [1. 1. 1. 1. 1.] 



In [94]:
#Changes in the NumPy array reflects in the tensor.
np.add(n, 1, out=n) #change in the numpy array
print(f"t: {t}")
print(f"n: {n}")

t: tensor([27., 27., 27., 27., 27.], dtype=torch.float64)
n: [27. 27. 27. 27. 27.]
