maxPooling
Max Pooling is a layer used in CNNs to reduce the size of feature maps while keeping the most important information.

MaxPool1d

In [1]:
import torch
import torch.nn as nn

x = torch.arange(1,17).float().reshape(1,1,16)

pool = nn.MaxPool1d(kernel_size=2)

y = pool(x)

print(y)

tensor([[[ 2.,  4.,  6.,  8., 10., 12., 14., 16.]]])


maxpool2d
let's take a exempl 

    1,2,3,4
    5,6,7,8
    9,10,11,12
    13,14,15,16
the kernele will glisse an in the it will take the max value ine his champs if we take  kernek_size = 2 so the windo is [1,2,5,6] then it take the ùax value which is 6 

In [4]:
import torch 
import torch.nn as nn 
x = torch.arange(1,17).float().reshape(1,1,4,4)

pool2d = nn.MaxPool2d(
    kernel_size=2,
    stride=1
)
y = pool2d(x)

print(x ,"\n")
print(y,"\n")




tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]]) 

tensor([[[[ 6.,  7.,  8.],
          [10., 11., 12.],
          [14., 15., 16.]]]]) 



it the same for the 3d maxpooling 
the parameter that takes by the function

nn.MaxPool1d(
    kernel_size,
    stride=None,
    padding=0,
    dilation=1,
    return_indices=False,
    ceil_mode=False
)

| Parameter        | Description                                                            |
| ---------------- | ---------------------------------------------------------------------- |
| `kernel_size`    | Size of the pooling window.                                            |
| `stride`         | How many elements the window moves each step. Default = `kernel_size`. |
| `padding`        | Adds zeros at both ends of the input.                                  |
| `dilation`       | Spacing between elements inside the pooling window.                    |
| `return_indices` | Returns the indices of maximum values (used by `MaxUnpool1d`).         |
| `ceil_mode`      | Uses `ceil()` instead of `floor()` when computing output size.         |


average pooling layers 
it's the same idea but it take the mean of the window that is see 

In [6]:
import torch 
import torch.nn as nn 
x = torch.arange(1,17).float().reshape(1,1,4,4)

pool2d = nn.AvgPool2d(
    kernel_size=2,
    stride=1
)
y = pool2d(x)

print(x ,"\n")
print(y,"\n")


tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]]) 

tensor([[[[ 3.5000,  4.5000,  5.5000],
          [ 7.5000,  8.5000,  9.5000],
          [11.5000, 12.5000, 13.5000]]]]) 



Additional parameter:
count_include_pad : include padded zeros in average calculation 

Adaptive Pooling Layers

These automatically choose the pooling region size to produce a desired output size.

In [16]:
import torch 
import torch.nn as nn 
x = torch.arange(1,17).float().reshape(1,1,4,4)

pool2d = nn.AdaptiveAvgPool2d(2)
y = pool2d(x)

print(x ,"\n")
print(y,"\n")
print(y.shape)





tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]]) 

tensor([[[[ 3.5000,  5.5000],
          [11.5000, 13.5000]]]]) 

torch.Size([1, 1, 2, 2])


No matter the input lenght 
100==> out_size
50==> out_size
10==> out_size


nn.AdaptiveAvgPool2d((1,1))
 used in architecture such resnet densenet efficientnet
 to convert :(batch, channels, H, W)
 into :(batch, channels, 1, 1) before the final classifier 

it's the same for all the adaptive max average 1D 2D 3D 
the main idea it' make the output is the same output_size automaticaly 

--------------------------------------------------------------------------

Fractionnal max avergre 1D 2D 3D 

1.nn.FractionalMaxPool2d
Normal maxpooling uses a fixed stride 
exemple nn.MaxPool2d(kernel_size=2, stride=2)

    4×4 → 2×2
    8×8 → 4×4
    16×16 → 8×8

the reduction factor is always fixed

but with FractionalMaxPool2d ,the reduction factor can be non-integer
exemple :32×32 → 20×20
instead od :32×32 → 16×16 or 32×32 → 8×8


In [17]:
import torch
import torch.nn as nn

x = torch.randn(1, 1, 8, 8)

pool = nn.FractionalMaxPool2d(
    kernel_size=2,
    output_size=(5,5)
)

y = pool(x)

print(y.shape)

torch.Size([1, 1, 5, 5])


Allows more flexibility in the output size.

Used in some research papers to add randomness and reduce overfitting.

2. nn.FractionalMaxPool3d
same idea but for 3D data 
input (N,C,D,H,W)


In [18]:
import torch
import torch.nn as nn

x = torch.randn(1, 1, 8, 8,8)


pool = nn.FractionalMaxPool3d(
    kernel_size=2,
    output_size=(5,5,5)
)

y = pool(x)

print(y.shape)

torch.Size([1, 1, 5, 5, 5])


-------------------------------------------------------------------------

LPPooling
LP Pooling is based on the Lp norm.
formula (somme de xi ^p)^1/p   
p norm degre 


In [ ]:
import torch
import torch.nn as nn

x = torch.tensor([[[3.,4.,5.,6.]]])

pool = nn.LPPool1d(
    norm_type=2,
    kernel_size=2
)
# for nrom_type= 2 is like a averge pooling 
#for nrom_type= infii  is like a max pooling 

y = pool(x)

print(y)

tensor([[[5.0000, 7.8102]]])


LP pooling is a compromise between
Average Pooling
      and
Max Pooling

p = 1  → close to Average Pooling
p = 2  → Euclidean norm
p = 10 → very close to Max Pooling
p → ∞  → Max Pooling

and is the same of 2D et 3D 

| Layer                 | Input Type     | Purpose                     |
| --------------------- | -------------- | --------------------------- |
| `FractionalMaxPool2d` | Images         | Flexible/random max pooling |
| `FractionalMaxPool3d` | Videos/Volumes | Flexible 3D max pooling     |
| `LPPool1d`            | Signals        | Lp-norm pooling             |
| `LPPool2d`            | Images         | Lp-norm pooling on images   |
| `LPPool3d`            | Volumes/Videos | Lp-norm pooling on 3D data  |


Average Pooling:
"Take the average"

Max Pooling:
"Take the strongest value"

LP Pooling:
"Take a value between average and max,
depending on p"

Fractional Max Pooling:
"Max Pooling with flexible output size"