maxPooling
Max Pooling is a layer used in CNNs to reduce the size of feature maps while keeping the most important information.

MaxPool1d

In [1]:
import torch
import torch.nn as nn

x = torch.arange(1,17).float().reshape(1,1,16)

pool = nn.MaxPool1d(kernel_size=2)

y = pool(x)

print(y)

tensor([[[ 2.,  4.,  6.,  8., 10., 12., 14., 16.]]])


maxpool2d
let's take a exempl 

    1,2,3,4
    5,6,7,8
    9,10,11,12
    13,14,15,16
the kernele will glisse an in the it will take the max value ine his champs if we take  kernek_size = 2 so the windo is [1,2,5,6] then it take the ùax value which is 6 

In [4]:
import torch 
import torch.nn as nn 
x = torch.arange(1,17).float().reshape(1,1,4,4)

pool2d = nn.MaxPool2d(
    kernel_size=2,
    stride=1
)
y = pool2d(x)

print(x ,"\n")
print(y,"\n")




tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]]) 

tensor([[[[ 6.,  7.,  8.],
          [10., 11., 12.],
          [14., 15., 16.]]]]) 



it the same for the 3d maxpooling 
the parameter that takes by the function

nn.MaxPool1d(
    kernel_size,
    stride=None,
    padding=0,
    dilation=1,
    return_indices=False,
    ceil_mode=False
)

| Parameter        | Description                                                            |
| ---------------- | ---------------------------------------------------------------------- |
| `kernel_size`    | Size of the pooling window.                                            |
| `stride`         | How many elements the window moves each step. Default = `kernel_size`. |
| `padding`        | Adds zeros at both ends of the input.                                  |
| `dilation`       | Spacing between elements inside the pooling window.                    |
| `return_indices` | Returns the indices of maximum values (used by `MaxUnpool1d`).         |
| `ceil_mode`      | Uses `ceil()` instead of `floor()` when computing output size.         |


average pooling layers 
it's the same idea but it take the mean of the window that is see 

In [6]:
import torch 
import torch.nn as nn 
x = torch.arange(1,17).float().reshape(1,1,4,4)

pool2d = nn.AvgPool2d(
    kernel_size=2,
    stride=1
)
y = pool2d(x)

print(x ,"\n")
print(y,"\n")


tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]]) 

tensor([[[[ 3.5000,  4.5000,  5.5000],
          [ 7.5000,  8.5000,  9.5000],
          [11.5000, 12.5000, 13.5000]]]]) 



Additional parameter:
count_include_pad : include padded zeros in average calculation 

Adaptive Pooling Layers

These automatically choose the pooling region size to produce a desired output size.

In [16]:
import torch 
import torch.nn as nn 
x = torch.arange(1,17).float().reshape(1,1,4,4)

pool2d = nn.AdaptiveAvgPool2d(2)
y = pool2d(x)

print(x ,"\n")
print(y,"\n")
print(y.shape)





tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]]) 

tensor([[[[ 3.5000,  5.5000],
          [11.5000, 13.5000]]]]) 

torch.Size([1, 1, 2, 2])


No matter the input lenght 
100==> out_size
50==> out_size
10==> out_size


nn.AdaptiveAvgPool2d((1,1))
 used in architecture such resnet densenet efficientnet
 to convert :(batch, channels, H, W)
 into :(batch, channels, 1, 1) before the final classifier 

it's the same for all the adaptive max average 1D 2D 3D 
the main idea it' make the output is the same output_size automaticaly 

--------------------------------------------------------------------------

Fractionnal max avergre 1D 2D 3D 

1.nn.FractionalMaxPool2d
Normal maxpooling uses a fixed stride 
exemple nn.MaxPool2d(kernel_size=2, stride=2)

    4×4 → 2×2
    8×8 → 4×4
    16×16 → 8×8

the reduction factor is always fixed

but with FractionalMaxPool2d ,the reduction factor can be non-integer
exemple :32×32 → 20×20
instead od :32×32 → 16×16 or 32×32 → 8×8


In [17]:
import torch
import torch.nn as nn

x = torch.randn(1, 1, 8, 8)

pool = nn.FractionalMaxPool2d(
    kernel_size=2,
    output_size=(5,5)
)

y = pool(x)

print(y.shape)

torch.Size([1, 1, 5, 5])


Allows more flexibility in the output size.

Used in some research papers to add randomness and reduce overfitting.

2. nn.FractionalMaxPool3d
same idea but for 3D data 
input (N,C,D,H,W)


In [18]:
import torch
import torch.nn as nn

x = torch.randn(1, 1, 8, 8,8)


pool = nn.FractionalMaxPool3d(
    kernel_size=2,
    output_size=(5,5,5)
)

y = pool(x)

print(y.shape)

torch.Size([1, 1, 5, 5, 5])


-------------------------------------------------------------------------

LPPooling
LP Pooling is based on the Lp norm.
formula (somme de xi ^p)^1/p   
p norm degre 


In [ ]:
import torch
import torch.nn as nn

x = torch.tensor([[[3.,4.,5.,6.]]])

pool = nn.LPPool1d(
    norm_type=2,
    kernel_size=2
)
# for nrom_type= 2 is like a averge pooling 
#for nrom_type= infii  is like a max pooling 

y = pool(x)

print(y)

tensor([[[5.0000, 7.8102]]])


LP pooling is a compromise between
Average Pooling
      and
Max Pooling

p = 1  → close to Average Pooling
p = 2  → Euclidean norm
p = 10 → very close to Max Pooling
p → ∞  → Max Pooling

and is the same of 2D et 3D 

| Layer                 | Input Type     | Purpose                     |
| --------------------- | -------------- | --------------------------- |
| `FractionalMaxPool2d` | Images         | Flexible/random max pooling |
| `FractionalMaxPool3d` | Videos/Volumes | Flexible 3D max pooling     |
| `LPPool1d`            | Signals        | Lp-norm pooling             |
| `LPPool2d`            | Images         | Lp-norm pooling on images   |
| `LPPool3d`            | Volumes/Videos | Lp-norm pooling on 3D data  |


Average Pooling:
"Take the average"

Max Pooling:
"Take the strongest value"

LP Pooling:
"Take a value between average and max,
depending on p"

Fractional Max Pooling:
"Max Pooling with flexible output size"

adaptive maxPool applies a 11d adaptive max pooling over a input signal 
give more flexibilite because y

question !!! 
what is the differnt between the adaptiveMaxPool ans FractionalMaxPool

=>Although FractionalMaxPool and AdaptiveMaxPool both reduce the size of a feature map using max pooling, they work in completely different ways.

1.AdaptiveMaxpool 
    You specify the output size, and PyTorch `automatically` chooses the kernel size and stride.
    You don't care about the pooling window.

=>why use it :if you have input a differnt image size and you want a one output value like (3*3)
This is why almost every CNN classifier uses Adaptive Pooling before the fully connected layer.

2.FractionalMaxPool 
    Fractional pooling is very different.
    Instead of choosing a fixed kernel size,
    it chooses non-uniform pooling regions.
    The pooling windows have different sizes.

    for exemple 
    instead of 
    2×2
    2×2
    2×2
    2×2

    it may choose 
    2×2
    3×2
    2×3
    3×3

    The regions are chosen randomly (or pseudo-randomly).
    suppose the input is 8x8
    and you want approxmately 5x5
    a normal maxpool cannot do this nicely because 8/5=1.6
    there is no kernel size 1.6 × 1.6 to give us  5x5 outpout images
    =>Fractional pooling solves this problem.

                Why use FractionalMaxPool?
                It was introduced in the paper:
                Fractional Max-Pooling (Benjamin Graham, 2014)
                The idea was to:
                reduce overfitting,
                introduce randomness similar to dropout,
                improve generalization,
                allow smoother reductions in feature map size.
                Instead of always shrinking by exactly 2,
                64 → 32 → 16 → 8
                you can shrink more gradually,
                64 → 45 → 32 → 22 → 16
                This preserves more information.

| Feature                  | AdaptiveMaxPool                                  | FractionalMaxPool                                        |
| ------------------------ | ------------------------------------------------ | -------------------------------------------------------- |
| Goal                     | Produce a specific output size                   | Produce a smaller output using irregular pooling regions |
| Pooling regions          | Computed deterministically                       | Chosen pseudo-randomly                                   |
| Randomness               | No                                               | Yes                                                      |
| Output size              | Exact                                            | Exact (`output_size`) or approximate (`output_ratio`)    |
| Kernel size              | Computed implicitly from the desired output      | Specified by the user (e.g., `kernel_size=2`)            |
| Typical use              | Standard CNNs, classifiers, variable-size inputs | Research, regularization, gradual downsampling           |
| Common in modern models? | **Very common**                                  | **Rare**                                                 |

                

In [5]:
import torch 
import torch.nn as nn 
x = torch.arange(1,17).float().reshape(1,1,4,4)

pool2d = nn.AdaptiveMaxPool2d((3,1))
y= pool2d(x)

print(x ,"\n")
print(y,"\n")
print(y.shape)


tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]]) 

tensor([[[[ 8.],
          [12.],
          [16.]]]]) 

torch.Size([1, 1, 3, 1])


-----------------------------------------------------------------

a Padding Layers adds extra values arouand the border of the input tensor before appling operations like convolution or pooling 
padding is mainly used to:
1.preserve the spatial size of the input .
2.prevent losing information at the bordes .
3.control the output size of convolution layers 

why is padding needed 
consider a 3*3 convolution kernel 
without padding :
    Input: 5×5
    Kernel: 3×3
    Stride: 1

output size :
        (5-3)/1 + 1 = 3 
        so 5*5 ====> 3*3
        problem the image becomes smaller

with padding =1 : the output is 5*5 

nn.ReflectionPad1d
pads a 1D tensor by reflecting mirroring the values at the boundary 
suppose we have 1234
the result is 
32|1234|32
padding = 2 


In [7]:
import torch 
import torch.nn as nn 

x = torch.tensor([1,2,3,4] ,dtype=float)
pad = nn.ReflectionPad1d(2)
y = pad(x.unsqueeze(0))
print(y)

tensor([[3., 2., 1., 2., 3., 4., 3., 2.]], dtype=torch.float64)


let's applied for 2D 
the same idea for the images (tensor 2D)

In [ ]:
import torch
import torch.nn as nn

x = torch.randint(9, (1,1,3,3))
#x = torch.randint(low=0, high=9, size=(1,1,3,3))

pad2d = nn.ReflectionPad2d(1)
y = pad2d(x)

print(x)
print()
print(y)

tensor([[[[8, 5, 1],
          [1, 1, 3],
          [6, 7, 1]]]])

tensor([[[[1, 1, 1, 3, 1],
          [5, 8, 5, 1, 5],
          [1, 1, 1, 3, 1],
          [7, 6, 7, 1, 7],
          [1, 1, 1, 3, 1]]]])


The border is created by mirroring the interior values, not by repeating the edge values.

nn.ZeroPad1d :pads is the input tennsir boudaires with zero .
let's take a exampl 2d 


In [16]:
import torch 
import torch.nn as nn 

x = torch.randint(low=1, high=17,size=(1,1,5,5))
pad0 = nn.ZeroPad2d(1)
y = pad0(x)

print(x)
print()
print(y)

tensor([[[[16, 13,  3, 15, 13],
          [10,  8,  9,  1, 16],
          [12, 13,  2, 13, 13],
          [16,  5,  4,  5, 16],
          [15,  9, 15,  8, 14]]]])

tensor([[[[ 0,  0,  0,  0,  0,  0,  0],
          [ 0, 16, 13,  3, 15, 13,  0],
          [ 0, 10,  8,  9,  1, 16,  0],
          [ 0, 12, 13,  2, 13, 13,  0],
          [ 0, 16,  5,  4,  5, 16,  0],
          [ 0, 15,  9, 15,  8, 14,  0],
          [ 0,  0,  0,  0,  0,  0,  0]]]])


nn.ConstantPad1d
Pads the input tensor boundaries with a constant value.you give its 

In [20]:
import torch 
import torch.nn as nn 

x = torch.randint(low=1, high=17,size=(1,1,5,5))

padConstant = nn.ConstantPad2d(1,9)
y = padConstant(x)
print(x)
print()
print(y)

tensor([[[[14, 13, 14,  5,  9],
          [ 1,  7, 16, 16, 12],
          [ 6,  4,  3, 14,  7],
          [13, 10,  5, 16, 15],
          [ 3,  2,  2,  7, 10]]]])

tensor([[[[ 9,  9,  9,  9,  9,  9,  9],
          [ 9, 14, 13, 14,  5,  9,  9],
          [ 9,  1,  7, 16, 16, 12,  9],
          [ 9,  6,  4,  3, 14,  7,  9],
          [ 9, 13, 10,  5, 16, 15,  9],
          [ 9,  3,  2,  2,  7, 10,  9],
          [ 9,  9,  9,  9,  9,  9,  9]]]])


nn.CircularPad1d
Pads the input tensor using circular padding of the input boundary.

In [27]:
import torch 
import torch.nn as nn 


x = torch.randint(low=1, high=17,size=(1,1,3,3))
padCirculaire = nn.CircularPad2d(1)

y = padCirculaire(x)
print(x)
print()
print(y)

tensor([[[[13,  6, 12],
          [ 7,  2, 13],
          [14, 16,  5]]]])

tensor([[[[ 5, 14, 16,  5, 14],
          [12, 13,  6, 12, 13],
          [13,  7,  2, 13,  7],
          [ 5, 14, 16,  5, 14],
          [12, 13,  6, 12, 13]]]])
